#!/usr/bin/env python3
"""
Script to help set up proper policies for the Supabase videos bucket.
This script generates the SQL commands needed to set up bucket policies.
"""

print("SUPABASE VIDEO BUCKET POLICIES SETUP")
print("=" * 50)
print()
print("To fix the storage access issue, you need to add these policies")
print("to your 'videos' bucket in the Supabase dashboard.")
print()
print("STEPS TO SET UP BUCKET POLICIES:")
print("-" * 35)
print("1. Go to your Supabase dashboard:")
print("   https://app.supabase.com/project/zbokocnaamwozkpjdqfu")
print()
print("2. Navigate to Storage → Buckets → videos")
print()
print("3. Click on the 'Policies' tab")
print()
print("4. Add the following policies:")
print()
print("POLICY 1 - Allow authenticated users to select (download) objects:")
print("- Policy Name: Allow authenticated users to select objects")
print("- Permission: SELECT")
print("- Roles: authenticated")
print("- Using Expression: (bucket_id = 'videos')")
print()
print("POLICY 2 - Allow authenticated users to insert (upload) objects:")
print("- Policy Name: Allow authenticated users to insert objects")
print("- Permission: INSERT")
print("- Roles: authenticated")
print("- With Check Expression: (bucket_id = 'videos')")
print()
print("POLICY 3 - Allow owners to update their objects:")
print("- Policy Name: Allow owners to update their objects")
print("- Permission: UPDATE")
print("- Roles: authenticated")
print("- Using Expression: (bucket_id = 'videos') AND (owner_id = auth.uid())")
print()
print("POLICY 4 - Allow owners to delete their objects:")
print("- Policy Name: Allow owners to delete their objects")
print("- Permission: DELETE")
print("- Roles: authenticated")
print("- Using Expression: (bucket_id = 'videos') AND (owner_id = auth.uid())")
print()
print("ALTERNATIVE: Run these SQL commands in the SQL Editor:")
print("-" * 50)
print()
print("-- Enable RLS on the storage objects table")
print("ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;")
print()
print("-- Policy to allow authenticated users to select objects in videos bucket")
print("CREATE POLICY \"Allow authenticated users to select objects\"")
print("ON storage.objects FOR SELECT")
print("TO authenticated")
print("USING (bucket_id = 'videos');")
print()
print("-- Policy to allow authenticated users to insert objects in videos bucket")
print("CREATE POLICY \"Allow authenticated users to insert objects\"")
print("ON storage.objects FOR INSERT")
print("TO authenticated")
print("WITH CHECK (bucket_id = 'videos');")
print()
print("-- Policy to allow owners to update their objects in videos bucket")
print("CREATE POLICY \"Allow owners to update their objects\"")
print("ON storage.objects FOR UPDATE")
print("TO authenticated")
print("USING (bucket_id = 'videos' AND owner_id = auth.uid());")
print()
print("-- Policy to allow owners to delete their objects in videos bucket")
print("CREATE POLICY \"Allow owners to delete their objects\"")
print("ON storage.objects FOR DELETE")
print("TO authenticated")
print("USING (bucket_id = 'videos' AND owner_id = auth.uid());")
print()
print("After setting up these policies, restart your application")
print("and try uploading a video again.")